### DISCUSSION TITLE
Is it really necessary for :indicator-indent to be less than :indent?

### DISCUSSION THREAD

**Discussion by theasp** [clj-commons/clj-yaml#37] [Q&A]
It seems to me that having `:indicator-indent` set to the same value as `:indent` would generate just as valid YAML as not.  For that matter, I think it would be also valid if it was greater.  Am I wrong?

**Comment by borkdude** [comment]
What part of the code are you referring to?

**Comment by theasp** [comment]
That was quite a while ago, but I think I wanted to set `{:indent 2 :indicator-indent 2}` so that instead of this:
```
user> (def data {:a [{:b 1} {:c 2} {:d 3} {:e {:aa 1 :bb 2 :cc 3}}]})
#'user/data
user> (println (clj-yaml.core/generate-string {:a [{:b 1} {:c 2} {:d 3} {:e {:aa 1 :bb 2 :cc 3}}]} :dumper-options {:indent 2  :flow-style :block}))
```

```yaml
a:
- b: 1
- c: 2
- d: 3
- e:
    aa: 1
    bb: 2
    cc: 3
````

I got:
```yaml
a:
  - b: 1
  - c: 2
  - d: 3
  - e:
      aa: 1
      bb: 2
      cc: 3
```

i.e. the list inside `a` is indented 2 spaces.
