### ISSUE TITLE
ci: deploy job fails for PRs

### ISSUE THREAD

**Issue by lread** [clj-commons/clj-yaml#40]
I think we can just not invoke this job if not on main branch?

I can take a look.

**Comment by lread** [comment]
@slipset, I think CircleCI allows us to not trigger a job [based on a matching tag only](https://circleci.com/docs/workflows#executing-workflows-for-a-git-tag).

We currently have:

```yaml
workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /Release-.*/
          context:
            - CLOJARS_DEPLOY
```

But unlike GitHub Actions, for CircleCI we can say, hey, only execute on matching tag please via `branches` filter:

```yaml
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /Release-.*/
            branches:
              ignore: /.*/
          context:
            - CLOJARS_DEPLOY
```

This is a confusing syntax, but I think it says don't trigger on any branch criteria, just trigger if you see a matching tag.

Is this what you'd like to happen?
